# -*- coding: utf-8 -*-
"""Linear Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8vLu8q5tdCooa_u-55f3ey75oOTi0Bu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

dataset = pd.read_csv("/content/Placement_1.csv")
dataset.head()

dataset.isnull().sum()

x = dataset["cgpa"]
x.ndim

x = dataset[["cgpa"]]
x.ndim

x = dataset[["cgpa"]]
y = dataset["package"]

sns.scatterplot(x="cgpa", y= "package",data=dataset)
plt.show()

x_train, x_test , y_train , y_test = train_test_split(x,y,test_size=0.2, random_state=30)

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train,y_train)

lr.coef_

lr.intercept_

lr.score(x_test,y_test)*100

lr.score(x_train,y_train)*100

lr.predict([[6.89]])

0.47676073*6.89-0.44511621958479264

y_prd = lr.predict(x)

plt.figure(figsize=(5,4))
sns.scatterplot(x="cgpa", y= "package",data=dataset)
plt.plot(dataset["cgpa"],y_prd , c="red")
plt.legend(["org data","predict line"])
plt.show()

